# GENERAL
scenario        : DYNAMIC_NORDNAV
ms_to_skip      : 0
ms_to_process   : 45000
ms_chunk_size   : 400
ms_read_size    : 200
in_file         : ./data/gpsDynamic_Nordnav_IF.bin
out_folder      : ./results
reference_pos_x : 0.0
reference_pos_y : 0.0
reference_pos_z : 0.0
log_level       : info

# RFSIGNAL
samp_freq        : 16.3676e6
intmd_freq       : 4.1304e6
is_complex       : false
bit_depth        : 8
signals          : gps_l1ca
max_channels     : 8
is_multi_antenna : false
n_ant            : 1

# ACQUISITION
doppler_range       : 5000.0
doppler_step        : 500.0
num_coh_per         : 1
num_noncoh_per      : 5
threshold           : 29.0
max_failed_attempts : 8

# TRACKING
min_converg_time_ms   : 100
tap_epl_wide          : 0.5
tap_epl               : 0.3
tap_epl_narrow        : 0.1
pll_bandwidth_wide    : 20.0
fll_bandwidth_wide    : 10.0
dll_bandwidth_wide    : 2.0
pll_bandwidth         : 10.0
fll_bandwidth         : 1.0
dll_bandwidth         : 0.25
pll_bandwidth_narrow  : 2.0
fll_bandwidth_narrow  : 0.01
dll_bandwidth_narrow  : 0.001

# MEASUREMENTS
meas_freq            : 5
process_std_vel      : 8.0
process_std_att      : 1.0
clock_model          : low_quality_tcxo
nominal_transit_time : 0.069
use_psr              : true
use_doppler          : true
use_adr              : false
use_cno              : true
do_vt                : false