# GENERAL
scenario        : THESIS_SIM
ms_to_process   : 60000
ms_chunk_size   : 400
ms_read_size    : 200
in_file         : ./data/sim-noise.iq
out_folder      : ./results
reference_pos_x : 422587.923
reference_pos_y : -5362823.257
reference_pos_z : 3415569.514
# sim-static  : 32.5863, -85.4943, 213.0
# sim-dynamic : 32.587056, -85.494430, 200.574
log_level       : info

# RFSIGNAL
samp_freq    : 12.5e6
intmd_freq   : 0.0
is_complex   : true
bit_depth    : 16
signals      : gps_l1ca
max_channels : 8

# ACQUISITION
doppler_range       : 5000.0
doppler_step        : 500.0
num_coh_per         : 1
num_noncoh_per      : 5
threshold           : 45.0
max_failed_attempts : 16

# TRACKING
min_converg_time_ms   : 100
tap_epl_wide          : 0.5
tap_epl               : 0.3
tap_epl_narrow        : 0.1
pll_bandwidth_wide    : 20.0
fll_bandwidth_wide    : 10.0
dll_bandwidth_wide    : 2.0
pll_bandwidth         : 10.0
fll_bandwidth         : 1.0
dll_bandwidth         : 0.25
pll_bandwidth_narrow  : 2.0
fll_bandwidth_narrow  : 0.01
dll_bandwidth_narrow  : 0.001

# MEASUREMENTS
meas_freq            : 5
process_std          : 1.0
clock_model          : low_quality_tcxo
nominal_transit_time : 0.068802
use_psr              : true
use_doppler          : true
use_adr              : false
use_cno              : true
do_vt                : false