scenario          : VT_ARRAY_CORRELATOR_SIM
clock_model       : high_quality_tcxo
vel_process_psd   : 10.0
att_process_psd   : 0.00005
sec_to_skip       : 28.1
# sec_to_skip       : 599.9
init_tow          : 413658.0
intmd_freq        : 0.0
sim_dt            : 0.01
meas_dt           : 0.02
tap_epl_wide      : 0.5
tap_epl           : 0.5
tap_epl_narrow    : 0.5
init_cb           : 0.0
init_cd           : 176.9
init_cov          : [9.0, 9.0, 9.0, 0.1, 0.1, 0.1, 0.01, 0.01, 0.01, 1.0, 0.05]
jammer_modulation : BPSK
jammer_type       : BLWN
j2s               : 0.0
add_init_err      : false
is_multi_antenna  : true
n_ant             : 4
ant_xyz_0         : [0.0, 0.0, 0.0]
ant_xyz_1         : [0.09514, 0.0, 0.0]
ant_xyz_2         : [0.0, -0.09514, 0.0]
ant_xyz_3         : [0.09514, -0.09514, 0.0]
data_file         : ./data/sim_truth.bin
ephem_file        : ./data/sim_ephem.bin
out_folder        : ./results
n_runs            : 20